IceCreamShop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [    
    # Сначала проверяем все пути, которые есть в приложении ice_cream
    path('', include('ice_cream.urls', namespace='ice_cream')),
    path('admin/', admin.site.urls),
    path('', include(('ice_cream.urls', 'ice_cream'), namespace='ice_cream')),
]

ice_cream/urls.py
from django.urls import path, include
from . import views

# Эта строчка обязательна. 
# Без нее чуда не произойдет и namespace работать не будет
app_name = 'ice_cream'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Список мороженого
    path('ice_cream/', views.ice_cream_list, name='ice_cream_list'),
    # Подробная информация о мороженом. Ждем пременную типа int, 
    # и будем использовать ее под именем pk
    path('ice_cream/<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
    path('', include(('ice_cream.urls', 'ice_cream'), namespace='ice_cream')),
]

ice_cream/models.py
from django.db import models

# Create your models here.
class IceCream(models.Model):
    name = models.CharField('Name', max_length=200)
    description = models.TextField('Discription')
    on_main = models.BooleanField('Go to the main page?', default=True)

    class Meta:        
        ordering = ('name',)

    def __str__(self):
        return f'{self.name}'

ice_cream/views.py
from django.shortcuts import render

from .models import IceCream


def index(request):
    template = 'ice_cream/index.html'
    selected_ice_creams = []
    # только то мороженое, у кторого есть флаг on_main
    context = {
        'selected_ice_creams': selected_ice_creams,
    }
    return render(request, template, context)


def ice_cream_list(request):
    template = 'ice_cream/ice_cream_list.html'
    ice_creams = []
    # все мороженое
    context = {
        'ice_creams': ice_creams,
    }
    return render(request, template, context)


def ice_cream_detail(request, pk):
    template = 'ice_cream/ice_cream_detail.html'
    ice_cream = []
    # Мороженое с id из запроса
    context = {
        'ice_cream': ice_cream,
    }
    return render(request, template, context)

templates/base.html
{% comment %} загрузка статики {% endcomment %}
{% load static %} 
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
<head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
    {% include 'includes/header.html' %}
    </header>
    <main>
    <div class="container py-2">
        {% block content %}
        Базовая страница
        {% endblock %}
    </div>
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
    {% include 'includes/footer.html' %}
    </footer>    
</body>
</html>

templates/ice_cream/ice_cream_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- py-1: контент внутри блока размещается с отсупом сверху и снизу -->      
<div class="container py-2">
<!-- py-3: контент внутри блока размещается с отсупом сверху и снизу -->
  <div class="row py-3">
  <!-- Блок картинки займет всю ширину родительского блока на мобильном, 
    5/12 на планшете и 1/4 на компьютере -->        
    <div class="col-12 col-md-5 col-xl-3" >
      <!--img-fluid: размер изображения подстроится под занимаемый блок -->
      <!-- img-thumbnail: вокруг изображения тонкая обводка -->
      <img class="img-fluid img-thumbnail" src="{% static 'img/tmb.png' %}" alt="">
    </div>
    <!-- Блок описания займет всю ширину родительского блока на мобильном, 
       7/12 на планшете и 3/4 на компьютере -->   
    <div class="col-12 col-md-7 col-xl-9">
      <h1>{{ ice_cream.name }}</h1>
      <p>{{ ice_cream.description }}</p>
    </div>
  </div>
</div> 
{% endblock %}

templates/ice_cream/ice_cream_list.html
{% extends 'base.html' %}
{% block content %}
  <h1>Полный список сортов мороженого</h1>
  <!-- py-3: контент внутри блока размещается с отсупом сверху и снизу --> 
  <div class="row py-3">
    {% for ice_cream in ice_creams %}
      {% include 'ice_cream/includes/ice_cream_card.html' %}  
    {% endfor %}
  </div>
{% endblock %}

templates/ice_cream/includes/ice_cream_card.html
{% load static %}

<!-- Блок с карточкой займет всю ширину родительского контейнера на мобильном, 
  половину на планшете и 1/4 на компьютере --> 
<!-- py-3: сделан внутренний отступ, что бы карточки не слипались -->
<div class="col-12 col-md-6 col-xl-3 p-3">
  <!-- h-100:  делает карточки одинаковой высоты -->
  <div class="card h-100">
    <!-- card-img-top: изображение размещается вверху карточки -->
    <!--img-fluid: размер изображения подстроится под занимаемый блок -->
    <img class="card-img-top img-fluid" src="{% static 'img/tmb.png' %}" alt="">
    <!-- card-body: текстовый контент карточки -->
    <div class="card-body">
      <h5>{{ ice_cream.name }}</h5>
    </div>
    <!-- btn: показывает что это кнопка  -->
    <!-- btn-success: определяет цвет кнопки --> 
    <a href="{% url 'ice_cream:ice_cream_detail' ice_cream.pk %}" class="btn btn-success">
      Подробная информация
    </a> 
  </div> <!-- Конец карточки -->
 </div> <!-- Конец блока определяющего размер элемента -->

templates/ice_cream/index.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
  <h1>Избранные сорта мороженого</h1>
  <!-- py-3: контент внутри блока размещается с отсупом сверху и снизу --> 
  <div class="row py-3">
    {% for ice_cream in selected_ice_creams %}
      {% include 'ice_cream/includes/ice_cream_card.html' %}  
    {% endfor %}
  </div>
{% endblock %}

templates/includes/footer.html
<p>© 2023 Copyright «Анфиса и друзья»</p> 

templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В качестве обёртки для пунктов меню выступает список  -->
<nav class="navbar navbar-dark navbar-expand-sm" style="background-color: green">
  <div class="container">
    <a class="navbar-brand" href="{% url 'ice_cream:index' %}">
       Анфиса для друзей
    </a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'ice_cream:ice_cream_list' %}">
          Все сорта мороженого
        </a>
      </li>
    </ul>
  </div>         
</nav>